[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.18.3 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "cd packages/cli && pnpm start"
